export enum ErrorType {
  // --- CONTENT ---
  CONTENT_OFF_TOPIC = "CONTENT_OFF_TOPIC",
  CONTENT_UNDEVELOPED_IDEAS = "CONTENT_UNDEVELOPED_IDEAS",
  CONTENT_LACK_EXAMPLES = "CONTENT_LACK_EXAMPLES",
  CONTENT_INCOHERENT_ARGUMENT = "CONTENT_INCOHERENT_ARGUMENT",

  // --- ORGANIZATION ---
  ORGANIZATION_POOR_TRANSITIONS = "ORGANIZATION_POOR_TRANSITIONS",
  ORGANIZATION_PARAGRAPH_STRUCTURE = "ORGANIZATION_PARAGRAPH_STRUCTURE",
  ORGANIZATION_LOGICAL_FLOW = "ORGANIZATION_LOGICAL_FLOW",
  ORGANIZATION_REPETITION = "ORGANIZATION_REPETITION",

  // --- GRAMMAR ---
  GRAMMAR_SUBJECT_VERB = "GRAMMAR_SUBJECT_VERB",
  GRAMMAR_TENSE = "GRAMMAR_TENSE",
  GRAMMAR_ARTICLE = "GRAMMAR_ARTICLE",
  GRAMMAR_PREPOSITION = "GRAMMAR_PREPOSITION",
  GRAMMAR_WORD_CHOICE = "GRAMMAR_WORD_CHOICE",
  GRAMMAR_SPELLING = "GRAMMAR_SPELLING",
  GRAMMAR_PUNCTUATION = "GRAMMAR_PUNCTUATION",
}
