-- CreateTable
CREATE TABLE `error` (
    `id` CHAR(36) NOT NULL,
    `errorType` ENUM('CONTENT_OFF_TOPIC', 'CONTENT_UNDEVELOPED_IDEAS', 'CONTENT_LACK_EXAMPLES', 'CONTENT_INCOHERENT_ARGUMENT', 'ORGANIZATION_POOR_TRANSITIONS', 'ORGANIZATION_PARAGRAPH_STRUCTURE', 'ORGANIZATION_LOGICAL_FLOW', 'ORGANIZATION_REPETITION', 'GRAMMAR_SUBJECT_VERB', 'GRAMMAR_TENSE', 'GRAMMAR_ARTICLE', 'GRAMMAR_PREPOSITION', 'GRAMMAR_WORD_CHOICE', 'GRAMMAR_SPELLING', 'GRAMMAR_PUNCTUATION') NOT NULL,
    `description` TEXT NOT NULL,
    `suggestion` TEXT NOT NULL,
    `startingPos` SMALLINT NOT NULL,
    `endingPos` SMALLINT NOT NULL,
    `criteriaId` CHAR(36) NOT NULL,
    `reviewId` CHAR(36) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `error` ADD CONSTRAINT `error_criteriaId_fkey` FOREIGN KEY (`criteriaId`) REFERENCES `criteria`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `error` ADD CONSTRAINT `error_reviewId_fkey` FOREIGN KEY (`reviewId`) REFERENCES `Review`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
